INCLUDE	=	/home/speedmax/code/apue/test_program/include
LIB	=		/home/speedmax/code/apue/test_program/lib/libapue.a
LD =		-lpthread
make:
	clang -I$(INCLUDE) -Wall data_location.c $(LIB) $(LD) -o data_location.out 
clean:
	rm -rf *.out
