INCLUDE	=	/home/speedmax/code/apue/test_program/include
LIB	=	/home/speedmax/code/apue/test_program/lib/libapue.a
make:
	clang -I$(INCLUDE) -Wall atexit_test.c $(LIB) -o atexit_test
clean:
	rm -rf *.out
